### ISSUE TITLE
InsectSelector: show opponent's pieces when + add selecting constraint

### ISSUE THREAD

**Issue by WardMaes** [WardMaes/hive#17]
- [ ] Update playerhand of opponent 
- [ ] Apply visual effects and onClick-logic to enable/disable some insects from placing

**Comment by bestrandomnameever** [comment]
Correctly show opponents pieces linked to #21 (either send playerHand updates or will happen automatically when machines sync states).

**Comment by bestrandomnameever** [comment]
Split into #43 and #44
